### ISSUE TITLE
Filter does not work on replies

### ISSUE THREAD

**Issue by wijayaerick** [mogproject/yay-filter#23]
### Yay Filter v0.1.5

- [x] Enable filter by default
- [x] Show filter button
- [x] Filter replies

**Languages**

- [ ] Enable Languages filter
- [ ] Use as a blocklist
- [x] English
- [x] Unknown

**Blocked words**

- [x] Enable word filter
- [ ] Use regex
```
read my
```

Expectation: works on both comments and replies
Actual: only works on comments, does not work on replies (found "don't `read my` name"  replies)

I tried with different word filters (copy from youtube comment replies directly), and it does not get filtered.

**Comment by mogproject** [comment]
Thanks for reporting. I'll work on this.

**Comment by mogproject** [comment]
Now the fixed version is available on Chrome Web Store.
